# Generated by Django 3.1.1 on 2020-09-07 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name of the cinema', max_length=200)),
                ('city', models.CharField(help_text='The city of the cinema', max_length=200)),
                ('address', models.CharField(help_text='The location of the cinema', max_length=200)),
            ],
            options={
                'verbose_name': 'Cinema',
                'verbose_name_plural': 'Cinemas',
                'db_table': 'cinema',
                'ordering': ['-id'],
                'get_latest_by': '-created_at',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name of the screen', max_length=200)),
                ('no_of_seats', models.DecimalField(decimal_places=2, help_text='The number of the seats available in the screen', max_digits=5)),
                ('cinema', models.ForeignKey(blank=True, help_text='The screen related with cinema', null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='The show date for the cinema')),
                ('time', models.TimeField(help_text='The show time for the cinema')),
                ('cinema', models.ForeignKey(blank=True, help_text='The cinema related with show', null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
                ('movie', models.ForeignKey(blank=True, help_text='The movie related with show', null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shows_screen', to='cinema.screen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the seat class', max_length=200)),
                ('cinema', models.ForeignKey(blank=True, help_text='The name of the cinemas', null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
            ],
        ),
    ]
