# Generated by Django 3.1.1 on 2020-09-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('seat_number', models.CharField(help_text='The seat number booked by the user', max_length=255)),
                ('no_of_tickets', models.DecimalField(decimal_places=2, help_text='The number of the tickets booked by the user', max_digits=5)),
                ('service_fee', models.FloatField(default=0.0, help_text='The service fee for bank of the tickets booked by the user')),
                ('total_cost', models.FloatField(default=0.0, help_text='The total cost of the tickets booked by the user')),
                ('seat_class', models.ForeignKey(help_text='The seat class booked by the user', on_delete=django.db.models.deletion.CASCADE, related_name='shows_seat_class', to='cinema.seatclass')),
                ('show', models.ForeignKey(help_text='The show booked by the user', on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='cinema.show')),
                ('user', models.ForeignKey(help_text='The person tickets booked by the user', on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
