# Generated by Django 3.1.1 on 2020-09-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name of the movie', max_length=200)),
                ('language', models.CharField(help_text='The audio language of the movie', max_length=200)),
                ('cast', models.CharField(blank=True, help_text='The group of actors who make up a movie', max_length=200, null=True)),
                ('director', models.CharField(blank=True, help_text='A person name who controls the making of a movie', max_length=200, null=True)),
                ('duration', models.FloatField(blank=True, help_text='Running time of a movie by hours', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movie',
                'ordering': ['-id'],
                'get_latest_by': '-created_at',
            },
        ),
    ]
